### ISSUE TITLE
smoldot-light: `Option::unwrap()` on a `None` value

### ISSUE THREAD

**Issue by lexnv** [smol-dot/smoldot#1318]
Hey, I see some asserts on the networking stack of smoldot:

```
2023-11-10T14:01:44.535504Z  INFO smoldot: Chain initialization complete for polkadot. Name: "Polkadot". Genesis hash: 0x91b1…90c3. Network identity: 12D3KooWFsE8oip3Fy2mRk7v6SjB2vTc7qPS7ZpQbxiKW7ETH8pi. Chain specification starting at: 0xaf96…8407 (#14442869)
2023-11-10T14:01:44.535571Z  INFO smoldot: Chain specification of polkadot contains a `genesis.raw` item. It is possible to significantly improve the initialization time by replacing the `"raw": ...` field with `"stateRootHash": "0x29d0d972cd27cbc511e9589fcb7a4506d5eb6a9e8df205f00472e5ab354a4e17"`
2023-11-10T14:01:44.585861Z  WARN connections: Failed to reach bootnode 12D3KooWKer8bYqpYjwurVABu13mkELpX2X7mSpEicpjShLeg7D6 through /dns/p2p.4.polkadot.network/tcp/30333: Failed to reach peer: Connection refused (os error 61). Because bootnodes constitue the access point of a chain, they are expected to be online at all time.
2023-11-10T14:01:44.764506Z  INFO smoldot: Parachain initialization complete for asset-hub-polkadot. Name: "Polkadot Asset Hub". Genesis hash: 0x68d5…de2f. Network identity: 12D3KooWBfXG94kdefYQgjNWAYs9DfJQmHgVDSub2Xyq7QmUjMxf. Relay chain: polkadot (id: 1000)
2023-11-10T14:01:44.764549Z  INFO smoldot: Chain specification of asset-hub-polkadot contains a `genesis.raw` item. It is possible to significantly improve the initialization time by replacing the `"raw": ...` field with `"stateRootHash": "0xc1ef26b567de07159e4ecd415fbbb0340c56a09c4d72c82516d0f3bc2b782c80"`
2023-11-10T14:01:44.764727Z  WARN json-rpc-polkadot: The JSON-RPC client has just called a JSON-RPC function from the legacy JSON-RPC API (chain_getFinalizedHead). Legacy JSON-RPC functions have loose semantics and cannot be properly implemented on a light client. You are encouraged to use the new JSON-RPC API <https://github.com/paritytech/json-rpc-interface-spec/> instead. The legacy JSON-RPC API functions will be deprecated and removed in the distant future.



2023-11-10T14:01:54.536274Z  WARN sync-service-polkadot: GrandPa warp sync in progress. Block: #16253508 (0x0x44d3…351b). Peer attempt: 12D3KooWQz2q2UWVCiy9cFX1hHYEmhSKQB2hjEZCccScHLGUPjcc.
2023-11-10T14:01:58.785426Z  INFO sync-service-polkadot: GrandPa warp sync finished to #18107400 (0x8266…ccb4)
2023-11-10T14:01:58.785775Z  INFO runtime-polkadot: Finalized block runtime ready. Spec version: 9431. Size of `:code`: 1.4 MiB.
2023-11-10T14:02:00.727280Z  WARN json-rpc-asset-hub-polkadot: The JSON-RPC client has just called a JSON-RPC function from the legacy JSON-RPC API (chain_getFinalizedHead). Legacy JSON-RPC functions have loose semantics and cannot be properly implemented on a light client. You are encouraged to use the new JSON-RPC API <https://github.com/paritytech/json-rpc-interface-spec/> instead. The legacy JSON-RPC API functions will be deprecated and removed in the distant future.



thread 'tasks-pool-4' panicked at /Users/lexnv/.cargo/registry/src/index.crates.io-6f17d22bba15001f/smoldot-0.12.0/src/libp2p/connection/yamux.rs:817:21:
assertion `left != right` failed
  left: 0
 right: 0
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'tasks-pool-0' panicked at /Users/lexnv/.cargo/registry/src/index.crates.io-6f17d22bba15001f/smoldot-light-0.10.0/src/network_service.rs:1797:22:
called `Option::unwrap()` on a `None` value
thread 'tasks-pool-2' panicked at /Users/lexnv/.cargo/registry/src/index.crates.io-6f17d22bba15001f/smoldot-light-0.10.0/src/sync_service/parachain.rs:321:91:
called `Option::unwrap()` on a `None` value
thread 'tasks-pool-1' panicked at /Users/lexnv/.cargo/registry/src/index.crates.io-6f17d22bba15001f/smoldot-light-0.10.0/src/network_service.rs:461:31:
called `Result::unwrap()` on an `Err` value: Canceled
```

I'm not able to reproduce this in a deterministic way, currently, I have applied on the parachain example from https://github.com/paritytech/subxt/pull/1238 the following diff, although I would suspect this to also happen without the diff:

```rust
+    let similar_chain: LightClient<PolkadotConfig> =
+        raw_light_client.for_chain(parachain_chain_id).await?;
+
     // Step 6. Subscribe to the finalized blocks of the chains.
+
+    let mut sub = similar_chain
+        .blocks()
+        .subscribe_all()
+        .await?
+        .map(|block| ("AssetHubBackend", block));
+    tokio::spawn(async move {
+        while let Some((chain, block)) = sub.next().await {
+            let block = block.expect("Block stream is infallible; qed");
+
+            println!(" Background     Chain {:?} hash={:?}", chain, block.hash());
+        }
+    });
+
```

I'm not sure if this was already handled by any prior work, wanted to report to be sure we don't miss anything here, thanks! 🙏

**Comment by tomaka** [comment]
https://github.com/smol-dot/smoldot/blob/e467848d25df373f55e108cb61462fe8aca533a3/lib/src/libp2p/connection/yamux.rs#L817

**Comment by tomaka** [comment]
The other three panics are the consequence of the panic in `yamux.rs` (channels get closed when they shouldn't).

From a quick glance it looks like this `debug_assert` is incorrect, while the logic around it is good, but it needs a careful review.

**Comment by lexnv** [comment]
Thanks for having a look at this! 🙏

**Comment by tomaka** [comment]
Reopening, as I've just stumbled upon:

> This is a bug in smoldot. Please open an issue at https://github.com/smol-dot/smoldot/issues with the following message:
panicked at /Users/tomaka/Projets/smoldot/lib/src/libp2p/connection/yamux.rs:784:21:
assertion failed: to_copy != 0 || expected_incoming_bytes.is_none()
