### ISSUE TITLE
UnresolvedFunctionImport  for Moonbeam Runtimes

### ISSUE THREAD

**Issue by albertov19** [smol-dot/smoldot#1561]
According to -> https://github.com/AcalaNetwork/chopsticks/issues/575

When using Moonbeam in the latest version of Chopsticks, and setting `allow-unresolved-imports` to `false`, you get:

```
npx @acala-network/chopsticks@latest -c moonbeam --allow-unresolved-imports false
Logs:

panicked at 'called `Result::unwrap()` on an `Err` value: VirtualMachine(UnresolvedFunctionImport { function: "ext_panic_handler_abort_on_panic_version_1", module_name: "env" })', src/task.rs:133:6

Stack:

Error
    at imports.wbg.__wbg_new_abda76e883ba8a5f (/home/purestake/.npm/_npx/81ad9c881cb83600/node_modules/@acala-network/chopsticks-executor/dist/cjs/chopsticks_executor.js:729:19)
    at wasm://wasm/009743be:wasm-function[728]:0x12aaea
    at wasm://wasm/009743be:wasm-function[886]:0x13420c
    at wasm://wasm/009743be:wasm-function[802]:0x12eaca
    at wasm://wasm/009743be:wasm-function[105]:0xa92ae
    at wasm://wasm/009743be:wasm-function[355]:0x10e846
    at wasm://wasm/009743be:wasm-function[937]:0x134a9e
    at __wbg_adapter_46 (/home/purestake/.npm/_npx/81ad9c881cb83600/node_modules/@acala-network/chopsticks-executor/dist/cjs/chopsticks_executor.js:407:10)
    at real (/home/purestake/.npm/_npx/81ad9c881cb83600/node_modules/@acala-network/chopsticks-executor/dist/cjs/chopsticks_executor.js:391:22)
    at node:internal/process/task_queues:141:7



node:internal/event_target:777
  process.nextTick(() => { throw err; });
                           ^
Error [RuntimeError]: unreachable
    at wasm://wasm/009743be:wasm-function[728]:0x12ac13
    at wasm://wasm/009743be:wasm-function[886]:0x13420c
    at wasm://wasm/009743be:wasm-function[802]:0x12eaca
    at wasm://wasm/009743be:wasm-function[105]:0xa92ae
    at wasm://wasm/009743be:wasm-function[355]:0x10e846
    at wasm://wasm/009743be:wasm-function[937]:0x134a9e
    at __wbg_adapter_46 (/home/purestake/.npm/_npx/81ad9c881cb83600/node_modules/@acala-network/chopsticks-executor/dist/cjs/chopsticks_executor.js:407:10)
    at real (/home/purestake/.npm/_npx/81ad9c881cb83600/node_modules/@acala-network/chopsticks-executor/dist/cjs/chopsticks_executor.js:391:22)
    
```

Chopsticks devs suggested that Moonbeam's new runtime has functions unknown to smoldot

**Comment by tomaka** [comment]
This indeed needs fixing in smoldot, but I want to point out that `allow_unresolved_functions: true` is fundamentally the correct setting when it comes to parachains, as parachains are free to add their own custom host functions.

**Comment by librelois** [comment]
@tomaka I get the same error even with `allow_unresolved_functions: true`.

**Comment by librelois** [comment]
@tomaka @albertov19 the host function `PanicHandler::abort_on_panic` is never called by our runtime because it's disabled by the rust feature `disable_panic_handler`.
So, for some reasons the chopsticks parameter `allow-unresolved-imports: true` doesn't work is not taken into account, the problem may come as much from chopsticks as from smoldot.

**Comment by tomaka** [comment]
The panic has been fixed in https://github.com/smol-dot/smoldot/pull/1570
