### ISSUE TITLE
panicked at /__w/smoldot/smoldot/lib/src/chain/async_tree.rs:868:9

### ISSUE THREAD

**Issue by ryanleecode** [smol-dot/smoldot#1963]
```log
panicked at /__w/smoldot/smoldot/lib/src/chain/async_tree.rs:868:9:
assertion failed: self.input_best_block_index.map_or(false,
    |current_input_best|
        self.non_finalized_blocks.is_ancestor(node_to_finalize,
            current_input_best))
```

Smoldot Version: 2.0.30

Line 9810

https://gist.github.com/ryanleecode/578a14bd6f185a299ce76f63997f0709#file-smoldot_crash-log-L9810

**Comment by ryanleecode** [comment]
This is dup of https://github.com/smol-dot/smoldot/issues/1901
