### ISSUE TITLE
CustomSectionsPresenceMismatch - Error on adding parachian

### ISSUE THREAD

**Issue by Douglasacost** [smol-dot/smoldot#595]
Hello. While adding a parachain chainSpec (e.x: Nodle parachain) to smoldot client versions from v1.0.3 to v1.0.6, the following error is logged and the client get stoped

```[smoldot] Smoldot v1.0.6
rococo_::  init
[smoldot] Chain initialization complete for rococo_v2_2. Name: "Rococo". Genesis hash: 0x6408…063e. State root hash: 0x8ad9dafeef04674f627ec2112f2206ed271b7270da5143fd11a943872c19f0da. Network identity: 12D3KooWMZPvLihSBdaenqyvHyQS5fqgnxGuWmNSxnhq3cTZfKGL. Chain specification or database starting at: 0xd5e1…d2b7 (#5137882)
/Users/douglasacosta/nodle/smoldot-play/node_modules/smoldot/dist/cjs/internals/client.js:8
        function fulfilled(value) { try { step(generator.next(value)); } catch (e) { reject(e); } }
                                                         ^
AddChainError: Failed to build genesis chain information: Error when initializing the virtual machine: Error in runtime spec Wasm sections: CustomSectionsPresenceMismatch
    at /Users/douglasacosta/nodle/smoldot-play/node_modules/smoldot/dist/cjs/internals/client.js:282:23
    at Generator.next (<anonymous>)
    at fulfilled (/Users/douglasacosta/nodle/smoldot-play/node_modules/smoldot/dist/cjs/internals/client.js:8:58)```

While on the browser with the version of smoldot client v1.0.2 I got this error below
<img width="849" alt="image" src="https://github.com/smol-dot/smoldot/assets/10488928/d165146e-0634-4ada-84b7-47a20c681b2c">

Chain info:
parachain chainspec: https://github.com/NodleCode/chain/blob/2.0.30/node/res/eden-testing.json
relay: rococo_v2_2
Platform:
Smoldot version: v1.0.3
Node version: v16.15.0
Processor: M1

**Comment by tomaka** [comment]
https://github.com/smol-dot/smoldot/pull/607 adds a work-around for the problem, and it should now work.
