### ISSUE TITLE
Unreachable code submitting transaction

### ISSUE THREAD

**Issue by lexnv** [smol-dot/smoldot#807]
While submitting a transaction to a local polkadot node I encountered the following error.

This is a bit hard to reproduce, I would say once every 7/8th transaction.
Not entirely sure if this is fixed since the 0.6.0 release 🙏 

```bash
cargo run --example unstable_light_client_tx_basic --features="unstable-light-client jsonrpsee"                                                              
   Compiling subxt v0.29.0 (/Users/lexnv/Workspace/parity/subxt/subxt)
   Compiling subxt-signer v0.29.0 (/Users/lexnv/Workspace/parity/subxt/signer)
    Finished dev [unoptimized + debuginfo] target(s) in 7.71s
     Running `target/debug/examples/unstable_light_client_tx_basic`
     
     
2023-06-23T11:13:19.883220Z  INFO smoldot: Chain initialization complete for dev. Name: "Development". Genesis hash: 0x4e1e…05c2. State root hash: 0x50e69d13db00a26a2834fa5ed6d6f2d99c5b965a6170da09b682c2e817f105ae. Network identity: 12D3KooWFJzLRTnqdCs8RBYCJWs7jEjuEduP82zCbTjthkpsCk5q. Chain specification or database starting at: 0x4e1e…05c2 (#0)
2023-06-23T11:13:19.883927Z  WARN json-rpc-dev: The JSON-RPC client has just called a JSON-RPC function from the legacy JSON-RPC API (chain_getBlockHash). Legacy JSON-RPC functions have loose semantics and cannot be properly implemented on a light client. You are encouraged to use the new JSON-RPC API <https://github.com/paritytech/json-rpc-interface-spec/> instead. The legacy JSON-RPC API functions will be deprecated and removed in the distant future.
thread 'smol-1' panicked at 'internal error: entered unreachable code', /Users/lexnv/.cargo/registry/src/index.crates.io-6f17d22bba15001f/smoldot-0.8.0/src/sync/all.rs:1024:39
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'smol-1' panicked at 'called `Result::unwrap()` on an `Err` value: SendError { kind: Disconnected }', /Users/lexnv/.cargo/registry/src/index.crates.io-6f17d22bba15001f/smoldot-light-0.6.0/src/sync_service.rs:211:14

```

```
2023-06-23T11:22:22.217901Z DEBUG jsonrpsee_client_transport::ws: Connecting to target: Target { sockaddrs: [127.0.0.1:9944], host: "127.0.0.1", host_header: "127.0.0.1:9944", _mode: Plain, path_and_query: "/" }
2023-06-23T11:22:22.220474Z TRACE soketto: read 321 bytes
2023-06-23T11:22:22.220916Z DEBUG jsonrpsee_client_transport::ws: Connection established to target: Target { sockaddrs: [], host: "127.0.0.1", host_header: "127.0.0.1:9944", _mode: Plain, path_and_query: "/" }
2023-06-23T11:22:22.223224Z TRACE soketto: read 2 bytes
2023-06-23T11:22:22.223255Z TRACE soketto::connection: 35c76e24: recv: (Ping (fin 1) (rsv 000) (mask (0 0)) (len 0))
2023-06-23T11:22:22.223337Z TRACE soketto::connection: 35c76e24: send: (Pong (fin 1) (rsv 000) (mask (1 4fd330f9)) (len 0))
2023-06-23T11:22:22.223357Z TRACE soketto::connection: 35c76e24: Receiver flushing connection
2023-06-23T11:22:22.223634Z TRACE method_call{method="sync_state_genSyncSpec"}: jsonrpsee_core::tracing: send="{\"jsonrpc\":\"2.0\",\"id\":0,\"method\":\"sync_state_genSyncSpec\",\"params\":[true]}"
2023-06-23T11:22:22.223819Z TRACE jsonrpsee_client_transport::ws: send: {"jsonrpc":"2.0","id":0,"method":"sync_state_genSyncSpec","params":[true]}
2023-06-23T11:22:22.223841Z TRACE soketto::connection: 35c76e24: send: (Text (fin 1) (rsv 000) (mask (1 44be0b0b)) (len 74))
2023-06-23T11:22:22.223986Z TRACE soketto::connection: 35c76e24: Sender flushing connection
2023-06-23T11:22:22.269736Z TRACE soketto: read 2 bytes
2023-06-23T11:22:22.269761Z TRACE soketto: read 8 bytes
2023-06-23T11:22:22.269768Z TRACE soketto::connection: 35c76e24: recv: (Text (fin 1) (rsv 000) (mask (0 0)) (len 2998034))
2023-06-23T11:22:22.323532Z TRACE method_call{method="sync_state_genSyncSpec"}: jsonrpsee_core::tracing: recv="{\"jsonrpc\":\"2.0\",\"result\":{\"badBlocks\":null,\"bootNodes\":[],\"chainType\":\"Development\",\"codeSubstitutes\":{},\"forkBlocks\":null,\"genesis\":{\"raw\":{\"childrenDefault\":{},\"top\":{\"0x06de3d8a54d27e44a9d5ce189618f22d4e7b9012096b41c4eb3aaf947f6ea429\":\"0x0500\",\"0x06de3d8a54d27e44a9d5ce189618f22db4b49d95320d9021994c850f25b8e385\":\"0x0000300000800000080000000000100000c8000005000000050000000200000002000000000000000000000000005000000010000700e87648170200400104000000040000000000000000000000000000000000000000000000000000000000000000000000080000000020000004000000040000000000100000b00400000000000000000000140000000400000004000000000000000000060000006400000002000000190000000000000002000000020000000700c817a80402004001000200000005000000\",\"0x074b65e262fcd5bd9c785caf7f42e00a4e7b9012096b41c4eb3aaf947f6ea429\":\"0x0000\",\"0x0f6738a0ee80c8e74cd2c7417c1e25564e7b9012096b41c4eb3aaf947f6ea429\":\"0x0100\",\"0x1405f2411d0af5a7ff397e7c9dc68d194e7b9012096b41c4eb3aaf947f6ea429\":\"0x0100\",\"0x1405f2411d0af5a7ff397e7c9dc68d196323ae84c43568be0d1394d5d0d522c4\":\"0x03000000\",\"0x1809d78346727a0ef58c0fa03bafa3234e7b9012096b41c4eb3aaf947f6ea429\":\"0x0000\",\"0x196e027349017067f9eb56e2c4d9ded54e7b9012096b41c4eb3aaf947f6ea429\":\"0x0000\",\"0x1a736d37504c2e3fb73dad160c55b2914e7b9012096b41c4eb3aaf947f6ea429\":\"0x0000\",\"0x1cb6f36e027abb2091cfb5110ab5087f4e7b9012096b41c4eb3aaf947f6ea429\":\"0x0000\",\"0x1cb6f36e027abb2091cfb5110ab5087f5e0621c4869aa60c02be9adcc98a0d1d\":\"0x04d43593c715fdd31c61141abd04a99fd6822c8558854ccde39a5684e7a56da27d0100000000000000\",\"0x1cb6f36e027abb2091cfb5110ab5087f66e8f035c8adbe7f1547b43c51e6f8a4\":\"0x00000000\",\"0x1cb6f36e027abb2091cfb5110ab5087faacf00b9b41fda7a9268821c2a2b3e4c\":\"0x04d43593c715fdd31c61141abd04a99fd6822c8558854ccde39a5684e7a56da27d0100000000000000\",\"0x1cb6f36e027abb2091cfb5110ab5087fdc6b171b77304263c292cc3ea5ed31ef\":\"0x0100000000000000040000000000000002\",\"0x2099d7f109d6e535fb000bba623fd4404c014e6bf8b8c2c011e7290b85696bb3\":\"0x04d43593c715fdd31c61141abd04a99fd6822c8558854ccde39a5684e7a56da27d\",\"0x2099d7f109d6e535fb000bba623fd4404e7b9012096b41c4eb3aaf947f6ea429\":\"0x0000\",\"0x2099d7f109d6e535fb000bba623fd4409f99a2ce711f3a31b2fc05604c93f179\":\"0x04d43593c715fdd31c61141abd04a99fd6822c8558854ccde39a5684e7a56da27d\",\"0x26aa394eea5630e07c48ae0c9558cef734abf5cb34d6244378cddbf18e849d96\":\"0x0000000007e0f78e940f7ec01d00\",\"0x26aa394eea5630e07c48ae0c9558cef74e7b9012096b41c4eb3aaf947f6ea429\":\"0x0000\",\"0x26aa394eea5630e07c48ae0c9558cef75684a022a34dd8bfa2baaf44f172b710\":\"0x01\",\"0x26aa394eea5630e07c48ae0c9558cef78a42f33323cb5ced3b44dd825fda9fcc\":\"0x4545454545454545454545454545454545454545454545454545454545454545\",\"0x26aa394eea5630e07c48ae0c9558cef7a44704b568d21667356a5a050c118746b4def25cfda6ef3a00000000\":\"0x4545454545454545454545454545454545454545454545454545454545454545\",\"0x26aa394eea5630e07c48ae0c9558cef7a7fd6c28836b9a28522dc924110cf439\":\"0x01\",\"0x26aa394eea5630e07c48ae0c9558cef7b99d880ec681799c0cf30e8886371da9007cbc1270b5b091758f9c42f5915b3e8ac59e11963af19174d0b94d5d78041c233f55d2e19324665bafdfb62925af2d\":\"0x000000000000000001000000000000000000c16ff28623000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000080\",\"0x26aa394eea5630e07c48ae0c9558cef7b99d880ec681799c0cf30e8886371da923a05cabf6d3bde7ca3ef0d11596b5611cbd2d43530a44705ad088af313e18f80b53ef16b36177cd4b77b846f2a5f07c\":\"0x000000000000000001000000000000000000c16ff28623000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000080\",\"0x26aa394eea5630e07c48ae0c9558cef7b99d880ec681799c0cf30e8886371da932a5935f6edc617ae178fef9eb1e211fbe5ddb1579b72e84524fc29e78609e3caf42e85aa118ebfe0b0ad404b5bdd25f\":\"0x000000000400000001000000000000000000c16ff28623000000000000000000000000000000000000000000000000000010a5d4e8000000000000000000000000000000000000000000000000000080\",\"0x26aa394eea5630e07c48ae0c9558cef7b99d880ec681799c0cf30e8886371da94f9aea1afa791265fae359272badc1cf8eaf04151687736326c9fea17e25fc5287613693c912909cb226aa4794f26a48\":\"0x000000000000000001000000000000000000c16ff2862300000000000000000000000000000000000000000000000000"
2023-06-23T11:22:22.324127Z DEBUG jsonrpsee_core::client::async_client: [backend]: Client dropped
2023-06-23T11:22:22.324240Z TRACE soketto::connection: 35c76e24: closing connection
2023-06-23T11:22:22.324310Z TRACE soketto::connection: 35c76e24: send: (Close (fin 1) (rsv 000) (mask (1 c442482e)) (len 2))
2023-06-23T11:22:22.324326Z TRACE soketto::connection: 35c76e24: Sender flushing connection
2023-06-23T11:22:22.351122Z TRACE light-client: Create light client
2023-06-23T11:22:23.427502Z DEBUG json-rpc-dev: PendingRequestsQueue <= {"jsonrpc":"2.0","id":"1", "method":"chain_getBlockHash","params":[0]}
2023-06-23T11:22:23.427569Z DEBUG json-rpc-dev: PendingRequestsQueue <= {"jsonrpc":"2.0","id":"2", "method":"state_getRuntimeVersion","params":[null]}
2023-06-23T11:22:23.427585Z DEBUG json-rpc-dev: PendingRequestsQueue <= {"jsonrpc":"2.0","id":"3", "method":"state_call","params":["Metadata_metadata_at_version","0xfffffff…
2023-06-23T11:22:23.428588Z  INFO smoldot: Chain initialization complete for dev. Name: "Development". Genesis hash: 0x4e1e…05c2. State root hash: 0x50e69d13db00a26a2834fa5ed6d6f2d99c5b965a6170da09b682c2e817f105ae. Network identity: 12D3KooWKKDE3BwKk8FYPuHBHvUzdo9McBv2GYHFPiG5UqZdhdRk. Chain specification or database starting at: 0x4e1e…05c2 (#0)
2023-06-23T11:22:23.428888Z DEBUG connections: OutSlots(dev) ∋ 12D3KooWEyoppNCUx8Yx66oV9fJnriXwCcXwDDUA2kj6vnc6iDEp
2023-06-23T11:22:23.429139Z DEBUG json-rpc-dev: PendingRequestsQueue => {"jsonrpc":"2.0","id":"1", "method":"chain_getBlockHash","params":[0]}
2023-06-23T11:22:23.429279Z  WARN json-rpc-dev: The JSON-RPC client has just called a JSON-RPC function from the legacy JSON-RPC API (chain_getBlockHash). Legacy JSON-RPC functions have loose semantics and cannot be properly implemented on a light client. You are encouraged to use the new JSON-RPC API <https://github.com/paritytech/json-rpc-interface-spec/> instead. The legacy JSON-RPC API functions will be deprecated and removed in the distant future.
2023-06-23T11:22:23.429412Z DEBUG json-rpc-dev: PendingRequestsQueue => {"jsonrpc":"2.0","id":"2", "method":"state_getRuntimeVersion","params":[null]}
2023-06-23T11:22:23.429425Z DEBUG json-rpc-dev: JSON-RPC <= {"jsonrpc":"2.0","id":"1","result":"0x4e1ef9781925d9ae357b112a5eac96b1476300e37d84f89208edb85ac35e05…
2023-06-23T11:22:23.429528Z TRACE light-client: RPC response Ok(RawValue("0x4e1ef9781925d9ae357b112a5eac96b1476300e37d84f89208edb85ac35e05c2"))
2023-06-23T11:22:23.429559Z DEBUG json-rpc-dev: PendingRequestsQueue => {"jsonrpc":"2.0","id":"3", "method":"state_call","params":["Metadata_metadata_at_version","0xfffffff…
2023-06-23T11:22:23.429675Z DEBUG runtime-dev: Worker <= Reset(finalized_block: 0x4e1e…05c2)
2023-06-23T11:22:23.429747Z DEBUG runtime-dev: Worker => NewDownload(block=0x4e1e…05c2)
2023-06-23T11:22:23.429817Z DEBUG connections: Pending(PendingId(0), 12D3KooWEyoppNCUx8Yx66oV9fJnriXwCcXwDDUA2kj6vnc6iDEp) started: /ip4/127.0.0.1/tcp/30333
2023-06-23T11:22:23.430054Z DEBUG runtime-dev: Worker <= FailedDownload(blocks=[0x4e1e…05c2], error=StorageQuery(StorageQueryError { errors: [] }))
2023-06-23T11:22:23.430554Z DEBUG connections: Pending(PendingId(0), 12D3KooWEyoppNCUx8Yx66oV9fJnriXwCcXwDDUA2kj6vnc6iDEp) => Connection through /ip4/127.0.0.1/tcp/30333
2023-06-23T11:22:23.433372Z DEBUG network: Connected(12D3KooWEyoppNCUx8Yx66oV9fJnriXwCcXwDDUA2kj6vnc6iDEp)
2023-06-23T11:22:23.434293Z DEBUG network: Connection(12D3KooWEyoppNCUx8Yx66oV9fJnriXwCcXwDDUA2kj6vnc6iDEp, dev) => ChainConnected(best_height=47, best_hash=0x63b7…3da6)
2023-06-23T11:22:23.434428Z DEBUG network: Connection(12D3KooWEyoppNCUx8Yx66oV9fJnriXwCcXwDDUA2kj6vnc6iDEp) <= GrandpaWarpSyncRequest(chain=dev, start=0x4e1e…05c2)
2023-06-23T11:22:23.436002Z DEBUG network: Connection(12D3KooWEyoppNCUx8Yx66oV9fJnriXwCcXwDDUA2kj6vnc6iDEp) => GrandpaWarpSyncRequest(chain=dev, num_fragments=1, finished=true)
2023-06-23T11:22:23.436618Z DEBUG sync-service-dev: Sync => WarpSyncFragmentVerified(sender=12D3KooWEyoppNCUx8Yx66oV9fJnriXwCcXwDDUA2kj6vnc6iDEp)
2023-06-23T11:22:23.436717Z DEBUG network: Connection(12D3KooWEyoppNCUx8Yx66oV9fJnriXwCcXwDDUA2kj6vnc6iDEp) <= StorageProofRequest(chain=dev, block=0x4f44…f395)
2023-06-23T11:22:23.438203Z DEBUG network: Connection(12D3KooWEyoppNCUx8Yx66oV9fJnriXwCcXwDDUA2kj6vnc6iDEp, dev) => GrandpaNeighborPacket(round_number=72, set_id=0, commit_finalized_height=45)
2023-06-23T11:22:23.438243Z DEBUG network: Connection(12D3KooWEyoppNCUx8Yx66oV9fJnriXwCcXwDDUA2kj6vnc6iDEp, dev) => GrandpaCommitMessage(target_block_hash=0x4f44…f395)
2023-06-23T11:22:23.438321Z DEBUG sync-service-dev: Sync <= IgnoredGrandpaCommit
2023-06-23T11:22:23.577011Z DEBUG network: Connection(12D3KooWEyoppNCUx8Yx66oV9fJnriXwCcXwDDUA2kj6vnc6iDEp) => StorageProofRequest(chain=dev, total_size=1.4 MiB)
2023-06-23T11:22:24.457409Z DEBUG sync-service-dev: Sync => WarpSyncRuntimeBuild(success=true, duration=880.189166ms)
2023-06-23T11:22:24.457486Z DEBUG network: Connection(12D3KooWEyoppNCUx8Yx66oV9fJnriXwCcXwDDUA2kj6vnc6iDEp) <= StorageProofRequest(chain=dev, block=0x4f44…f395)
2023-06-23T11:22:24.457686Z DEBUG network: Connection(12D3KooWEyoppNCUx8Yx66oV9fJnriXwCcXwDDUA2kj6vnc6iDEp) <= CallProofRequest(dev, 0x4f44…f395, BabeApi_configuration)
2023-06-23T11:22:24.457787Z DEBUG network: Connection(12D3KooWEyoppNCUx8Yx66oV9fJnriXwCcXwDDUA2kj6vnc6iDEp) <= CallProofRequest(dev, 0x4f44…f395, BabeApi_next_epoch)
2023-06-23T11:22:24.457945Z DEBUG network: Connection(12D3KooWEyoppNCUx8Yx66oV9fJnriXwCcXwDDUA2kj6vnc6iDEp) <= CallProofRequest(dev, 0x4f44…f395, BabeApi_current_epoch)
2023-06-23T11:22:24.458522Z DEBUG network: Connection(12D3KooWEyoppNCUx8Yx66oV9fJnriXwCcXwDDUA2kj6vnc6iDEp, dev) => BlockAnnounce(best_hash=0x4f44…f395, is_best=false)
2023-06-23T11:22:24.458571Z DEBUG network: Connection(12D3KooWEyoppNCUx8Yx66oV9fJnriXwCcXwDDUA2kj6vnc6iDEp, dev) => BlockAnnounce(best_hash=0xc307…db58, is_best=true)
2023-06-23T11:22:24.458640Z DEBUG sync-service-dev: Sync <= BlockAnnounce(sender=12D3KooWEyoppNCUx8Yx66oV9fJnriXwCcXwDDUA2kj6vnc6iDEp, hash=0x4f44…f395, is_best=false, parent_hash=0xaccc…3799)
2023-06-23T11:22:24.458660Z DEBUG sync-service-dev: Sync => Discarded
2023-06-23T11:22:24.458690Z DEBUG sync-service-dev: Sync <= BlockAnnounce(sender=12D3KooWEyoppNCUx8Yx66oV9fJnriXwCcXwDDUA2kj6vnc6iDEp, hash=0xc307…db58, is_best=true, parent_hash=0x63b7…3da6)
2023-06-23T11:22:24.458733Z DEBUG sync-service-dev: Sync => Discarded
2023-06-23T11:22:24.458992Z DEBUG network: Connection(12D3KooWEyoppNCUx8Yx66oV9fJnriXwCcXwDDUA2kj6vnc6iDEp) => IdentifyRequest
2023-06-23T11:22:24.599656Z DEBUG network: Connection(12D3KooWEyoppNCUx8Yx66oV9fJnriXwCcXwDDUA2kj6vnc6iDEp) => CallProofRequest(dev, total_size: 1.1 kiB)
2023-06-23T11:22:24.599778Z DEBUG network: Connection(12D3KooWEyoppNCUx8Yx66oV9fJnriXwCcXwDDUA2kj6vnc6iDEp) => CallProofRequest(dev, total_size: 1.1 kiB)
2023-06-23T11:22:24.599831Z DEBUG network: Connection(12D3KooWEyoppNCUx8Yx66oV9fJnriXwCcXwDDUA2kj6vnc6iDEp) => CallProofRequest(dev, total_size: 1.1 kiB)
2023-06-23T11:22:24.604393Z DEBUG sync-service-dev: Sync => WarpSyncBuildChainInformation(success=true)
2023-06-23T11:22:24.604415Z DEBUG network: Connection(12D3KooWEyoppNCUx8Yx66oV9fJnriXwCcXwDDUA2kj6vnc6iDEp) => StorageProofRequest(chain=dev, total_size=1.4 MiB)
thread 'smol-1' panicked at 'internal error: entered unreachable code', /Users/lexnv/.cargo/registry/src/index.crates.io-6f17d22bba15001f/smoldot-0.8.0/src/sync/all.rs:1024:39
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'smol-1' panicked at 'called `Result::unwrap()` on an `Err` value: SendError { kind: Disconnected }', /Users/lexnv/.cargo/registry/src/index.crates.io-6f17d22bba15001f/smoldot-light-0.6.0/src/sync_service.rs:211:14
2023-06-23T11:22:25.879052Z DEBUG network: Connection(12D3KooWEyoppNCUx8Yx66oV9fJnriXwCcXwDDUA2kj6vnc6iDEp, dev) => GrandpaCommitMessage(target_block_hash=0x4f44…f395)
2023-06-23T11:22:27.757036Z DEBUG network: Connection(12D3KooWEyoppNCUx8Yx66oV9fJnriXwCcXwDDUA2kj6vnc6iDEp, dev) => BlockAnnounce(best_hash=0x0b0f…9916, is_best=false)
2023-06-23T11:22:28.435527Z DEBUG connections: On chain dev, discovered:
2023-06-23T11:22:30.024896Z DEBUG network: Connection(12D3KooWEyoppNCUx8Yx66oV9fJnriXwCcXwDDUA2kj6vnc6iDEp, dev) => BlockAnnounce(best_hash=0xd4d2…0084, is_best=true)
2023-06-23T11:22:30.385004Z DEBUG network: Connection(12D3KooWEyoppNCUx8Yx66oV9fJnriXwCcXwDDUA2kj6vnc6iDEp, dev) => GrandpaCommitMessage(target_block_hash=0x0b0f…9916)
2023-06-23T11:22:31.761270Z DEBUG network: Connection(12D3KooWEyoppNCUx8Yx66oV9fJnriXwCcXwDDUA2kj6vnc6iDEp, dev) => BlockAnnounce(best_hash=0x63b7…3da6, is_best=false)
2023-06-23T11:22:34.168772Z DEBUG network: Connection(12D3KooWEyoppNCUx8Yx66oV9fJnriXwCcXwDDUA2kj6vnc6iDEp, dev) => GrandpaCommitMessage(target_block_hash=0x63b7…3da6)
2023-06-23T11:22:36.018040Z DEBUG network: Connection(12D3KooWEyoppNCUx8Yx66oV9fJnriXwCcXwDDUA2kj6vnc6iDEp, dev) => BlockAnnounce(best_hash=0xf0f9…16f8, is_best=true)
2023-06-23T11:22:37.904649Z DEBUG network: Connection(12D3KooWEyoppNCUx8Yx66oV9fJnriXwCcXwDDUA2kj6vnc6iDEp, dev) => GrandpaCommitMessage(target_block_hash=0x63b7…3da6)
```

The subxt PR for testing: https://github.com/paritytech/subxt/pull/965

**Comment by tomaka** [comment]
Thanks!

This code has basically zero tests :grimacing:
