### ISSUE TITLE
Smoldot has panicked while executing task `sync-service-polkadot`

### ISSUE THREAD

**Issue by josepot** [smol-dot/smoldot#956]
After upgrating to the latest version of substrate-connect (which uses smoldot@1.0.13), I started getting the error in the title of this issue.

These are the logs:

```
[smoldot] Smoldot v1.0.13
[smoldot] Chain initialization complete for polkadot. Name: "Polkadot". Genesis hash: 0x91b1…90c3. State root hash: 0x29d0d972cd27cbc511e9589fcb7a4506d5eb6a9e8df205f00472e5ab354a4e17. Network identity: 12D3KooWJMX7iATKvQkgJ5iWwDtmdeyrZeNMRokDp1LNaNfkSzqK. Chain specification or database starting at: 0x9e9f…ff49 (#16464786)
Smoldot has panicked while executing task `sync-service-polkadot`. This is a bug in smoldot. Please open an issue at https://github.com/smol-dot/smoldot/issues with the following message:
panicked at 'called `Option::unwrap()` on a `None` value', /__w/smoldot/smoldot/light-base/src/sync_service/standalone.rs:1193:78
Error
    at panic (file:///home/projects/stackblitz-starters-j52yw9/node_modules/smoldot/dist/mjs/internals/local-instance.js:76:23)
    at wasm://wasm/012bd0ae:wasm-function[6978]:0x18e0a3
    at wasm://wasm/012bd0ae:wasm-function[3256]:0xc86b0
    at wasm://wasm/012bd0ae:wasm-function[16257]:0x345320
    at wasm://wasm/012bd0ae:wasm-function[16247]:0x34458b
    at wasm://wasm/012bd0ae:wasm-function[16246]:0x3444ed
    at wasm://wasm/012bd0ae:wasm-function[16252]:0x344d4c
    at wasm://wasm/012bd0ae:wasm-function[16353]:0x34b5fa
    at wasm://wasm/012bd0ae:wasm-function[16360]:0x34bba5
    at wasm://wasm/012bd0ae:wasm-function[2015]:0x5f9b4
```

**Comment by tomaka** [comment]
Do you have logs with a better log level by any chance?

**Comment by josepot** [comment]
> Could you generate logs with a better log level by any chance?

```
[smoldot] Smoldot v1.0.13
[json-rpc-polkadot] JSON-RPC => {"jsonrpc":"2.0","id":1,"method":"chainHead_unstable_genesisHash","params":[]}
[json-rpc-polkadot] JSON-RPC => {"jsonrpc":"2.0","id":2,"method":"chainHead_unstable_follow","params":[true]}
[smoldot] Chain initialization complete for polkadot. Name: "Polkadot". Genesis hash: 0x91b1…90c3. State root hash: 0x29d0d972cd27cbc511e9589fcb7a4506d5eb6a9e8df205f00472e5ab354a4e17. Network identity: 12D3KooWQptjKLtjgiewaxEBrqUy6AvkCp4PmgdThG663Ngo2VPq. Chain specification or database starting at: 0x9e9f…ff49 (#16464786)
[connections] OutSlots(polkadot) ∋ 12D3KooWEPmjoRpDSUuiTjvyNDd8fejZ9eNWH5bE965nyBMDrB4o
[connections] OutSlots(polkadot) ∋ 12D3KooWLvcA24g6sT9YTaQyinwowMbLF5z7iMLoxZpEiV9pSmNf
[connections] OutSlots(polkadot) ∋ 12D3KooWEsPEadSjLAPyxckqVJkp54aVdPuX3DD6a1FTL2y5cB9x
[connections] OutSlots(polkadot) ∋ 12D3KooWKer8bYqpYjwurVABu13mkELpX2X7mSpEicpjShLeg7D6
[runtime-polkadot] Worker <= Reset(finalized_block: 0x9e9f…ff49)
[runtime-polkadot] Worker => NewDownload(block=0x9e9f…ff49)
[connections] Pending(PendingId(0), 12D3KooWLvcA24g6sT9YTaQyinwowMbLF5z7iMLoxZpEiV9pSmNf) started: /dns/polkadot-connect-1.parity.io/tcp/443/wss
[connections] Pending(PendingId(1), 12D3KooWEPmjoRpDSUuiTjvyNDd8fejZ9eNWH5bE965nyBMDrB4o) started: /dns/polkadot-connect-0.parity.io/tcp/443/wss
[connections] Pending(PendingId(2), 12D3KooWKer8bYqpYjwurVABu13mkELpX2X7mSpEicpjShLeg7D6) started: /dns/p2p.4.polkadot.network/tcp/30333
[connections] Pending(PendingId(2), 12D3KooWKer8bYqpYjwurVABu13mkELpX2X7mSpEicpjShLeg7D6) => ReachFailed(addr=/dns/p2p.4.polkadot.network/tcp/30333, known-unreachable=true, error="Invalid multiaddr")
[connections] Pending(PendingId(3), 12D3KooWEsPEadSjLAPyxckqVJkp54aVdPuX3DD6a1FTL2y5cB9x) started: /dns/polkadot-connect-3.parity.io/tcp/443/wss
[json-rpc-polkadot] JSON-RPC <= {"jsonrpc":"2.0","id":1,"result":"0x91b171bb158e2d3848fa23a9f1c25182fb8e20313b2c1eb49219da7a70ce90c3…
[runtime-polkadot] Worker <= FailedDownload(blocks=[0x9e9f…ff49], error=StorageQuery(StorageQueryError { errors: [] }))
[connections] OutSlots(polkadot) ∋ 12D3KooWBKtPpCnVTTzD7fPpCdFsrsYZ5K8fwmsLabb1JBuCycYs
[connections] Pending(PendingId(2), 12D3KooWBKtPpCnVTTzD7fPpCdFsrsYZ5K8fwmsLabb1JBuCycYs) started: /dns/polkadot-connect-6.parity.io/tcp/443/wss
[connections] Pending(PendingId(3), 12D3KooWEsPEadSjLAPyxckqVJkp54aVdPuX3DD6a1FTL2y5cB9x) => Connection through /dns/polkadot-connect-3.parity.io/tcp/443/wss
[connections] Pending(PendingId(1), 12D3KooWEPmjoRpDSUuiTjvyNDd8fejZ9eNWH5bE965nyBMDrB4o) => Connection through /dns/polkadot-connect-0.parity.io/tcp/443/wss
[connections] Pending(PendingId(0), 12D3KooWLvcA24g6sT9YTaQyinwowMbLF5z7iMLoxZpEiV9pSmNf) => Connection through /dns/polkadot-connect-1.parity.io/tcp/443/wss
[connections] Pending(PendingId(2), 12D3KooWBKtPpCnVTTzD7fPpCdFsrsYZ5K8fwmsLabb1JBuCycYs) => Connection through /dns/polkadot-connect-6.parity.io/tcp/443/wss
[network] Connected(12D3KooWEsPEadSjLAPyxckqVJkp54aVdPuX3DD6a1FTL2y5cB9x)
[network] Connected(12D3KooWLvcA24g6sT9YTaQyinwowMbLF5z7iMLoxZpEiV9pSmNf)
[network] Connected(12D3KooWEPmjoRpDSUuiTjvyNDd8fejZ9eNWH5bE965nyBMDrB4o)
[network] Connected(12D3KooWBKtPpCnVTTzD7fPpCdFsrsYZ5K8fwmsLabb1JBuCycYs)
[network] Connection(12D3KooWEsPEadSjLAPyxckqVJkp54aVdPuX3DD6a1FTL2y5cB9x, polkadot) => ChainConnected(best_height=16568141, best_hash=0x7bea…faae)
[network] Connection(12D3KooWEsPEadSjLAPyxckqVJkp54aVdPuX3DD6a1FTL2y5cB9x) <= GrandpaWarpSyncRequest(chain=polkadot, start=0x9e9f…ff49)
[network] Connection(12D3KooWLvcA24g6sT9YTaQyinwowMbLF5z7iMLoxZpEiV9pSmNf, polkadot) => ChainConnected(best_height=16568141, best_hash=0x7bea…faae)
[network] Connection(12D3KooWLvcA24g6sT9YTaQyinwowMbLF5z7iMLoxZpEiV9pSmNf, polkadot) => GrandpaNeighborPacket(round_number=18141, set_id=1521, commit_finalized_height=16568138)
[network] Connection(12D3KooWEsPEadSjLAPyxckqVJkp54aVdPuX3DD6a1FTL2y5cB9x) => GrandpaWarpSyncRequest(chain=polkadot, num_fragments=13, finished=true)
[sync-service-polkadot] Sync => WarpSyncFragmentVerified(sender=12D3KooWEsPEadSjLAPyxckqVJkp54aVdPuX3DD6a1FTL2y5cB9x)
[sync-service-polkadot] Sync => WarpSyncFragmentVerified(sender=12D3KooWEsPEadSjLAPyxckqVJkp54aVdPuX3DD6a1FTL2y5cB9x)
[sync-service-polkadot] Sync => WarpSyncFragmentVerified(sender=12D3KooWEsPEadSjLAPyxckqVJkp54aVdPuX3DD6a1FTL2y5cB9x)
[sync-service-polkadot] Sync => WarpSyncFragmentVerified(sender=12D3KooWEsPEadSjLAPyxckqVJkp54aVdPuX3DD6a1FTL2y5cB9x)
[sync-service-polkadot] Sync => WarpSyncFragmentVerified(sender=12D3KooWEsPEadSjLAPyxckqVJkp54aVdPuX3DD6a1FTL2y5cB9x)
[sync-service-polkadot] Sync => WarpSyncFragmentVerified(sender=12D3KooWEsPEadSjLAPyxckqVJkp54aVdPuX3DD6a1FTL2y5cB9x)
[sync-service-polkadot] Sync => WarpSyncFragmentVerified(sender=12D3KooWEsPEadSjLAPyxckqVJkp54aVdPuX3DD6a1FTL2y5cB9x)
[sync-service-polkadot] Sync => WarpSyncFragmentVerified(sender=12D3KooWEsPEadSjLAPyxckqVJkp54aVdPuX3DD6a1FTL2y5cB9x)
[sync-service-polkadot] Sync => WarpSyncFragmentVerified(sender=12D3KooWEsPEadSjLAPyxckqVJkp54aVdPuX3DD6a1FTL2y5cB9x)
[sync-service-polkadot] Sync => WarpSyncFragmentVerified(sender=12D3KooWEsPEadSjLAPyxckqVJkp54aVdPuX3DD6a1FTL2y5cB9x)
[sync-service-polkadot] Sync => WarpSyncFragmentVerified(sender=12D3KooWEsPEadSjLAPyxckqVJkp54aVdPuX3DD6a1FTL2y5cB9x)
[sync-service-polkadot] Sync => WarpSyncFragmentVerified(sender=12D3KooWEsPEadSjLAPyxckqVJkp54aVdPuX3DD6a1FTL2y5cB9x)
[sync-service-polkadot] Sync => WarpSyncFragmentVerified(sender=12D3KooWEsPEadSjLAPyxckqVJkp54aVdPuX3DD6a1FTL2y5cB9x)
[network] Connection(12D3KooWEsPEadSjLAPyxckqVJkp54aVdPuX3DD6a1FTL2y5cB9x) <= StorageProofRequest(chain=polkadot, block=0xdfaa…df82)
[network] Connection(12D3KooWEPmjoRpDSUuiTjvyNDd8fejZ9eNWH5bE965nyBMDrB4o, polkadot) => GrandpaNeighborPacket(round_number=18141, set_id=1521, commit_finalized_height=16568138)
Smoldot has panicked while executing task `sync-service-polkadot`. This is a bug in smoldot. Please open an issue at https://github.com/smol-dot/smoldot/issues with the following message:
panicked at 'called `Option::unwrap()` on a `None` value', /__w/smoldot/smoldot/light-base/src/sync_service/standalone.rs:1193:78
Error
    at panic (file:///home/projects/stackblitz-starters-j52yw9/node_modules/smoldot/dist/mjs/internals/local-instance.js:76:23)
    at wasm://wasm/012bd0ae:wasm-function[6978]:0x18e0a3
    at wasm://wasm/012bd0ae:wasm-function[3256]:0xc86b0
    at wasm://wasm/012bd0ae:wasm-function[16257]:0x345320
    at wasm://wasm/012bd0ae:wasm-function[16247]:0x34458b
    at wasm://wasm/012bd0ae:wasm-function[16246]:0x3444ed
    at wasm://wasm/012bd0ae:wasm-function[16252]:0x344d4c
    at wasm://wasm/012bd0ae:wasm-function[16353]:0x34b5fa
    at wasm://wasm/012bd0ae:wasm-function[16360]:0x34bba5
    at wasm://wasm/012bd0ae:wasm-function[2015]:0x5f9b4
```

**Comment by tomaka** [comment]
https://github.com/smol-dot/smoldot/blob/a0db6881f421af18386f6f4d68f16f296bae9d23/light-base/src/sync_service/standalone.rs#L1193

**Comment by tomaka** [comment]
Bug is here and is very stupid: https://github.com/smol-dot/smoldot/blob/172784cd9af400081e000eda49fd0148b1e0e087/light-base/src/network_service.rs#L991-L994
